version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install
      - run:
          name: Ejecutar script de prueba
          command: node app.js
workflows:
  version: 2
  preproduccion_workflow:
  jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  preproduccion:
    jobs:
      - build
      - test

