version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install
      - run:
          name: Ejecutar script de prueba
          command: node app.js
workflows:
  version: 2
  preproduccion_workflow:
    jobs:
      - build
